# THIS FILE CONTAINS SEVERAL CONFIGURATION VARIABLES
# IT SHOULD BE CHANGED EVERYTIME A NEW RELEASE WILL BE DEPLOYED

CURRENT_VERSION = "v1.3"

# WINDOW_SIZE="500x600"

DATABASE = "database.db"

LOGGER_FILE = "log.txt"