name: TalemDeploy
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build binary
      run: |
        pyinstaller mainWindows.spec
    - name: ZIP binary
      run: |
        Compress-Archive -Path ${{ github.workspace }}\dist\* -CompressionLevel Optimal -DestinationPath ${{ github.workspace }}\Release.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.zip
        asset_name: Release.zip
        tag: ${{ github.ref }}
        overwrite: true
        